# Netlify configuration for a monorepo with a Next.js frontend and Python backend.

# Base build settings for the entire project.
[build]
  # The base directory for the build, relative to the root.
  base = "frontend"
  # The build command, run from the base directory.
  command = "npm install && npm run build"
  # The directory that contains the deploy-ready assets, relative to the base directory.
  publish = ".next"
  # The directory where serverless functions are located, relative to the root.
  functions = "../backend/app"

[build.environment]
  PYTHON_VERSION = "3.11"


# This rewrite rule directs all requests to /api/v1/* to the Python serverless function.
# This mimics the routing configuration present in your vercel.json file.
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
